services:
  task-api:
    tty: true
    container_name: task-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
